# @register

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "fullName": "test",
  "email": "test",
  "password": "123",
  "role": "admin"
}

### Login Request to your Ktor Backend
# @name login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test",
  "password": "123"
}

> {%
    // Assuming your server returns a JSON like { "token": "ey..." }
    // Adjust `response.body.token` if your JSON field name is different
    client.global.set("bearer_token", response.body.token);
%}
###

# @name project
POST http://localhost:8080/admin/projects
Content-Type: application/json
Authorization: Bearer {{bearer_token}}

{
  "description": "desc",
  "updatedAt": "2025-06-16T14:00:00",
  "createdAt": "2025-06-16T14:00:00",
  "budget": 900,
  "endDate": "2025-10-01",
  "location": "tash",
  "managerId": "2c06eab3-ba0a-4dd5-ae4d-21f49a4d8d94",
  "name": "eshonguzar",
  "startDate": "2025-10-01",
  "status": "ACTIVE",
  "employeeIds": []
}

###
# @name getProjects
GET http://localhost:8080/admin/projects
Content-Type: application/json
Authorization: Bearer {{bearer_token}}


###
GET http://localhost:8080/admin/employees
Content-Type: application/json
Authorization: Bearer {{bearer_token}}
