ktor:
  application:
    modules:
      - com.fahr.hrplatform.ApplicationKt.module
  deployment:
    port: 8080
  security:
    jwt:
      secret: "your_secret_key_here"
      issuer: "com.fahr.hrplatform"
      audience: "com.fahr.hrplatform.users"
      realm: "Access to HR Platform"

  database:
    driverClassName: "org.h2.Driver"
    jdbcURL: "jdbc:h2:file:./build/db;DB_CLOSE_DELAY=-1"
    user: "root"
    password: "r"
